### ISSUE TITLE
24-06-17(월) 스크럼

### ISSUE THREAD

**Issue by 2897robo** [nhnacademy-be6-5ritang/NHN_BookStore#123]
###   - 오늘 할것-
- [x] 포트 포워딩 8080 -> 80
- [ ] 아키텍처 정밀 설계 + 그림

- [x] FRONT 템플릿 결정 -> https://themeforest.net/item/smartbooks-responsive-book-store-ecommerce-bootstrap-4-template/23493015
- [x] 템플릿 결제

- 프로젝트 세팅
- - [ ] CLOUD GATEWAY - 이기훈
- - [x] (저번 주는 테스트) 프로젝트(프론트, 백, 게이트웨이)에 CI / CD 구축 - 김다운

- [x] 디자인 패턴 및 프로젝트 폴더 구조 결정(MVC 패턴)
- [x] 스프링 프로젝트 생성 -> [FRONT] Controller ("/") API, 디렉토리 구조
- [x] 스프링 프로젝트 생성 -> [BACK] API, 데이터베이스 연결, 디렉토리 구조 등
- [x] 와이어 프레임 작성 - Figma 회원가입
- [x] API 개발 분담
- [x] ERD 기반 역할 분담(와이어 프레임, API 개발)
- - 주문/결제 김다운
- - 도서 김기욱
- - 쿠폰 이기훈
- - 파일-리뷰, 위시리스트, 카트(장바구니) 이경헌
- - 회원 김태환
- - 포인트 + 베송 박창대

- - 어제 뭐 했고, 오늘 뭐 하고 무슨 이슈가 있었다고 알림 -> 스크럼(10~15분)
- - 이후 회의가 필요한 부분을 따로 진행

- [x] 깃 컨벤션 정하기 - https://velog.io/@shin6403/Git-git-%EC%BB%A4%EB%B0%8B-%EC%BB%A8%EB%B2%A4%EC%85%98-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0
- [x] 코딩 컨벤션 정하기 - 네이버 자바 컨벤션

### - 회의 내용
> - (체크 된 거 다 끝)
> - ERD에서 식별 관계들 비식별로 수정
> - ERD 회원 - 주문 관계 제거
> - 템플릿 Header, Footer 제거 여부 및 수정 여부는 추후 재결정

### - TODO
> - 와이어프레임 작성
> - 와이어프레임 FLOW 연결
> - API 개발
> - CI/CD 구축 + CLOUD GATEWAY 구축
