### ISSUE TITLE
24-06-18(화) 스크럼

### ISSUE THREAD

**Issue by Daun0808** [nhnacademy-be6-5ritang/NHN_BookStore#128]
### - TODO
> - JWT 기반 인증
> - 로깅

### - 10시 스크럼
- [x] gateway 구축 확인
- [X] 기능구현 일정 지정
- [X] api 구현 진행률 확인
- [X] erd_v2.1 버전업 

### - 오늘 할 것
- gateway와 eureka에 서버 연결 - 이기훈,김태환,김기욱
- 각자 맡은 기능에 대한 일정 지정 후 api 구현
