### ISSUE TITLE
24-07-16(화) 스크럼

### ISSUE THREAD

**Issue by monte-kim** [nhnacademy-be6-5ritang/NHN_BookStore#174]
### - TODO
개인 과제
> - 이력서 제출
> - 개인 주제 발표 영상
> - 테스트 케이스 작성 (영상 제출일까지 60% 이상) (각자)

팀 과제
- [ ] 프로젝트 소개 영상 제출 (1번 영상) (22일 월요일 9시까지)
- [ ] 프로젝트 소개자료 제출

- [ ] 검색기능 -> 김기욱 (망해도 내일까지 끝내야함)
- [ ] 테스트 케이스 작성 (영상 제출일까지 60% 이상) (각자) **21일 일요일 모임 전까지 각자 끝내오기**
- [x] Cache 적용하기 (이경헌)
- [ ] 로깅 logback 과 log&crash -> 이경헌
- [ ] secure key manager -> 김기욱
- [ ] 책 설명 등록시 위즈윅 에디터 사용 (이건 뭔가요?)-> 이경헌
      https://ui.toast.com/tui-editor
- [ ] 프론트 에러 페이지 맵핑 -> [프론트 서버 에러] 401, 404, 409, 500, 502, 403 / [FEIGN CLIENT(500) 에러] DeocdeError 맵핑 -> 김다운, 김태환 (21일 일요일)
- [ ] SWAGGER API 명세서 작성 -> 이기훈(일단 쿠폰만) (19일 금요일)

- [ ] 다국어처리 (i18n) - 김태환

### - 10시 스크럼
> - 현재까지의 진행 상황
> - 전체 남은 것
> - 나머지 중 오늘 할 것
> - ***팀 과제 배분***

### - 전체 남은 것
> - 이경헌 : 테스트 코드, 팀 과제
> - 김기욱 : 검색 기능, 팀 과제
> - 이기훈 : Validation 처리, 쿠폰 적용 후 사용 완료 처리(with 다운), 에러, 프론트
> - 김다운 : Validation 처리, 다건주문 절반 구현, 결제 페이지 연결
> - 김태환 : Validation 처리, 회원 관리자 기능(권한 부여), 권한 별 AOP, UI 변경

### - 어제 한 것
> - 이경헌 : 리뷰 포인트 적립 끝
> - 김기욱 : elastic search 학습
> - 이기훈 : RabbitMQ 끝, 유효성 검사 구현 중
> - 김다운 : 세션에서 서비스로 쿠폰 적용 수정했음, 쿠폰 적용까지 사용자 테스트 함, 결제 전 페이지에서 결제 연결
> - 김태환 : 메인 페이지 디자인 수정, 메인 페이지 책 10권 채움

### - 팀 과제 배분                       // 예정 완료 일자
**[최우선은 아님]** 시연 영상을 위해 시연만 완벽하면 되기 때문에 기능 구현이 최우선
| 팀원 | 과제명 | 마감 일정 |
| --- | --- | --- |
| 이경헌 | logback, logcrash / 책 설명란 위즈윅 에디터 적용 | 21일(일)(안 되면 이 다음 주) |
| 김기욱 | Secure Key Manager | 19일(금) |
| 이기훈 | Swagger API 명세서 작성 (일단 쿠폰만) | 19일(금) |
| 김다운 | 프론트 에러 페이지 맵핑 | 21일(일) 모임 전까지 |
| 김태환 | 프론트 에러 페이지 맵핑, **[시연을 위한 우선]UI 수정** | 21일(일) 모임 전까지 |
