### ISSUE TITLE
23-07-18(목) 스크럼

### ISSUE THREAD

**Issue by monte-kim** [nhnacademy-be6-5ritang/NHN_BookStore#179]
### - TODO
개인 과제
> - 이력서 제출
> - 개인 주제 발표 영상
> - 테스트 케이스 작성 (영상 제출일까지 60% 이상) (각자)

팀 과제
- [ ] 프로젝트 소개 영상 제출 (1번 영상) (22일 월요일 9시까지)
- [ ] 프로젝트 소개자료 제출

- [ ] 검색기능 -> 김기욱 (망해도 오늘까지 끝내야함)
- [ ] 테스트 케이스 작성 - [주의] 로직이 변경되어도 테스트는 통과되어야 한다.
(영상 제출일(22일 오전 9시)까지 60% 이상) (각자) **21일 일요일 모임 전까지 각자 끝내오기**

- [x] 로깅 logback 과 log&crash -> 이경헌
- [ ] secure key manager -> 이경헌
- [x] 책 설명 등록시 위즈윅 에디터 사용 (이건 뭔가요?)-> 이경헌
      https://ui.toast.com/tui-editor
- [x] 프론트 에러 페이지 맵핑 -> [프론트 서버 에러] 401, 404, 409, 500, 502, 403 / [FEIGN CLIENT(500) 에러] DeocdeError 맵핑 -> 김다운, 김태환 (21일 일요일, 시간 부족하면 영상 제출 이후)
- [ ] SWAGGER API 명세서 작성 -> 이기훈(일단 쿠폰만) (19일 금요일)

- [ ] 다국어처리 (i18n)

### 이슈
- [x] PROD 환경에서 dev 실행됨

### - 10시 스크럼
> - 현재까지의 진행 상황
> - 전체 남은 것
> - 나머지 중 오늘 할 것
> - ***팀 과제 배분***

### - 전체 남은 것
> - 이경헌 : 캐싱 처리 -> redis cache 수정, secure key manager
> - 김기욱 : 검색 기능, 테스트 코드
> - 이기훈 : 프론트(금 완료), 테스트 코드, Swagger API
> - 김다운 : Validation 처리, 테스트 코드
> - 김태환 : Validation 처리, 테스트 코드, UI 변경, 다국어 처리(생략 가능)

### - 어제 한 것
> - 이경헌 : 위즈윅 에디터, validation 처리 끝,
> - 김기욱 : 서버 메모리 수정(가상 메모리 -> 3GB로 증량) -> 서버 터짐 방지, elastic search(도커), 키바나, 로그 stash 연동 끝
> - 이기훈 : validation 처리, 쿠폰 사용됨 처리 끝, 쿠폰 프론트
> - 김다운 : 다건 결제 완료, 관련 에러 처리, 프론트 alert 창 처리
> - 김태환 : UI 수정

### - 오늘 할 것
> - 이경헌 : logback&logcrash, 테스트 코드
> - 김기욱 : 검색 백, 프론트 연결
> - 이기훈 : validation 처리 마무리, 쿠폰 프론트 마무리, SWAGGER API 학습
> - 김다운 : (관리자) 포장지 생성, (관리자) 주문 상태 생성
> - 김태환 : validation 처리, UI 수정(**회원 포인트**)

### Validation 처리
- @NotNull, @Length, Controller layer에 @Valid [@RequestBody, @ModelAttribute 앞에]

### - 팀 과제 배분                       // 예정 완료 일자
**[최우선은 아님]** 시연 영상을 위해 시연만 완벽하면 되기 때문에 기능 구현이 최우선
| 팀원 | 과제명 | 마감 일정 |
| --- | --- | --- |
| 이경헌 | logback, logcrash / 책 설명란 위즈윅 에디터 적용 | 21일(일)(안 되면 이 다음 주) |
| 김기욱 | Secure Key Manager | 19일(금) |
| 이기훈 | Swagger API 명세서 작성 (일단 쿠폰만) | 19일(금) |
| 김다운 | 프론트 에러 페이지 맵핑 | 21일(일) 모임 전까지 |
| 김태환 | 프론트 에러 페이지 맵핑, **[시연을 위한 우선]UI 수정** | 21일(일) 모임 전까지 |
