### ISSUE TITLE
24-07-22(월) 스크럼

### ISSUE THREAD

**Issue by 2897robo** [nhnacademy-be6-5ritang/NHN_BookStore#182]
### - TODO
개인 과제
> - 개인 주제 발표 영상
> - 테스트 케이스 작성 (영상 제출일까지 60% 이상) (각자)

팀 과제
- [x] 프로젝트 소개 영상 제출 (1번 영상) (22일 월요일 9시까지)
- [x] 프로젝트 소개자료 제출
- [x] 에러 찾아보기 (어떤 상황, 어떤 에러)
- [ ] 테스트 케이스 작성 - [주의] 로직이 변경되어도 테스트는 통과되어야 한다.
(영상 제출일(22일 오전 9시)까지 60% 이상) (각자) **21일 일요일 모임 전까지 각자 끝내오기**
- [ ] secure key manager -> 이경헌
- [ ] Back 테스트 마무리
- [ ] Front 테스트, Account 테스트, Coupon 테스트
- [ ] SonarQube code smell 제거
- [ ] UI 수정
- [ ] SWAGGER API 명세서 작성 -> 백, 회원
- [ ] 다국어처리 (i18n)

### - 전체 남은 것
> - 이경헌 : secure key manager, 테스트코드
> - 김기욱 : 테스트 코드
> - 이기훈 : 테스트 코드, Swagger API
> - 김다운 : 테스트 코드, 결제 확장성 고려 설계
> - 김태환 : 테스트 코드, UI 변경, 다국어 처리(생략 가능)

### - 어제 한 것
> - 이경헌 : 프론트 테스트 코드, log&crash 배포환경 설정
> - 김기욱 : ppt, 영상
> - 이기훈 : readme.md 작성, 쿠폰 테스트 코드
> - 김다운 : 백, 프론트 테스트코드
> - 김태환 : 아키텍쳐, 영상 편집

### - 오늘 할 것
> - 이경헌 : 백 테스트 코드, 부족한 기능들
> - 김기욱 : 로그아웃 버그 해결
> - 이기훈 : 쿠폰, 프론트 테스트코드
> - 김다운 : 백 주문 테스트코드 재작성
> - 김태환 : 무.

### Validation 처리
- @NotNull, @Length, Controller layer에 @Valid [@RequestBody, @ModelAttribute 앞에]
