### ISSUE TITLE
24-07-30(화) 스크럼

### ISSUE THREAD

**Issue by Daun0808** [nhnacademy-be6-5ritang/NHN_BookStore#189]
### - TODO
개인 과제
> - 테스트 케이스 작성 (80% 이상) (각자)

팀 과제
- [ ] 테스트 케이스 작성 - [주의] 로직이 변경되어도 테스트는 통과되어야 한다.
- [ ] secure key manager -> 이경헌
- [ ] Back 테스트 마무리
- [ ] Front 테스트, Account 테스트, Coupon 테스트
- [ ] SonarQube code smell 제거
- [ ] SWAGGER API 명세서 작성 -> 백, 인증

### - 오늘 할 것
프론트 잔 에러, 버그들 모두 찾아 수정할 것
> - 1. 페이코 로그인 시 에러 - 김태환
> - 2. 주소 추가시 상세주소 미입력시 에러 발생 ( 프론트에서 require 처리 예정) - (해결) 김태환
> - 3. 책 등록시 이미지 업로드 위치 - (해결) 이경헌
> - 4. 검색시 정렬 - 김기욱 (해결)
> - 5. 사이드바 변경 문제 (회원 주문 상세 ) - (해결) 김다운
> - 6. Footer.html 에 깃허브 주소 추가 - (해결) 김태환
> - 7. 검색 기능 개선 - 김기욱 (해결안할거임)
> - 8. 검색시 정렬 및 프론트 통일 - 김기욱 (해결)
> - 9. 휴면 계정 AOP 처리 - 김태환 (해결)
> - 10. 관리자 권한 부여 기능 -  (해결) 김다운
> - 11. 인증 서버 테스트 - 김태환
> - 12. 회원 정보 수정 - (해결)김다운
> - 13. 결제 확장성 고려 설계 - (해결) 김다운
> - 14. 깃허브 리드미 프로필 링크 - 김기욱 (해결)

### - 전체 남은 것
> - 이경헌 : secure key manager, 테스트코드 , Swagger API
> - 김기욱 : 테스트 코드
> - 이기훈 : 테스트 코드
> - 김다운 : 테스트 코드, 결제 확장성 고려 설계
> - 김태환 : 테스트 코드, Swagger API

### Validation 처리
- @NotNull, @Length, Controller layer에 @Valid [@RequestBody, @ModelAttribute 앞에]

### Swagger 처리
- @Tag, @Operation, @ApiResponse 작성
