### ISSUE TITLE
24-07-31(수) 스크럼

### ISSUE THREAD

**Issue by Daun0808** [nhnacademy-be6-5ritang/NHN_BookStore#190]
### - TODO
개인 과제
> - 테스트 케이스 작성 (80% 이상) (각자)

팀 과제
- [ ] 테스트 케이스 작성 - [주의] 로직이 변경되어도 테스트는 통과되어야 한다.
- [ ] secure key manager -> 이경헌
- [ ] Back 테스트 마무리
- [x] Account 테스트
- [ ] Coupon 테스트
- [ ] SWAGGER API 명세서 작성 -> 백
- [x] SWAGGER API 명세서 작성 -> 인증

### - 오늘 할 것
프론트 잔 에러, 버그들 모두 찾아 수정할 것
> - 1. 페이코 로그인 시 에러 - 김태환 (진행중)
> - 2. 검색 기능 개선 - 김기욱 (해결안할거임)

### - 전체 남은 것
> - 이경헌 : secure key manager, 테스트코드 , Swagger API
> - 김기욱 : 테스트 코드
> - 이기훈 : 테스트 코드
> - 김다운 : 테스트 코드
> - 김태환 : 테스트 코드

### Validation 처리
- @NotNull, @Length, Controller layer에 @Valid [@RequestBody, @ModelAttribute 앞에]

### Swagger 처리
- @Tag, @Operation, @ApiResponse 작성
